In [8]:
#module 1.1
class Employee:
    company_name = 'ABC Company' 

    def __init__(self, name, salary):  
        self.name = name
        self.salary = salary 

    def show(self):
        print('Employee:', self.name, self.salary, self.company_name)
emp1.show()

emp2 = Employee("Emma", 10000)
emp2.show()


Employee: Harry 12000 ABC Company
Employee: Emma 10000 ABC Company


In [10]:
#Module 1.2
class Employee:
    def __init__(self, name, salary): 
        self.name = name
        self._salary = salary

    def show(self):
        print("Name is", self.name, "and salary is", self._salary)

emp = Employee("Jessa", 40000)
emp.show()
print(emp._salary)


Name is Jessa and salary is 40000
40000


In [12]:
#polymorphism
class Circle:
    pi = 3.14
    
    def __init__(self, radius):  
        self.radius = radius

    def calculate_area(self):
        print("Area of circle:", self.pi * self.radius * self.radius)

class Rectangle:
    def __init__(self, length, width): 
        self.length = length
        self.width = width

    def calculate_area(self):
        print("Area of Rectangle:", self.length * self.width)

def area(shape):
    shape.calculate_area()

cir = Circle(5)
rect = Rectangle(10, 5)

area(cir)
area(rect)


Area of circle: 78.5
Area of Rectangle: 50


In [13]:

class Vehicle:
    def __init__(self, name, color, price):
        self.name = name
        self.color = color
        self.price = price

    def info(self):
        print(self.name, self.color, self.price)

class Car(Vehicle):
    def change_gear(self, no):
        print(self.name, 'changes gear to number', no)

# Create object of Car
car = Car('BMW X1', 'Black', 35000)
car.info()
car.change_gear(5)


BMW X1 Black 35000
BMW X1 changes gear to number 5


In [14]:
#a simple counter that increments by 1 and allows changing the value of the internal counter.
def counter(maximum):
    i = 0
    while i < maximum:
        val = (yield i)  

        
        if val is not None:
            i = val
        else:
            i += 1


In [15]:
#Numpy
import numpy as np
x=np.random.randint(10,30,6)
print(x)

[27 25 27 16 10 15]


In [16]:
import numpy as np
x=np.random.random((10,5))
print(x)
new=x[:5]
print("New array=",new)

[[0.62417187 0.26976575 0.16580524 0.14824141 0.75917656]
 [0.12274187 0.87076401 0.15939465 0.16245522 0.96750397]
 [0.85711225 0.70324038 0.32441737 0.21844199 0.58730831]
 [0.29834035 0.75706156 0.07626642 0.18021305 0.31397457]
 [0.51121686 0.78273326 0.18743182 0.11838632 0.62552314]
 [0.58583157 0.90544849 0.92490682 0.41660924 0.0574585 ]
 [0.86453075 0.45909467 0.62925819 0.5918376  0.56836866]
 [0.91421638 0.42787716 0.09352867 0.48985817 0.86172612]
 [0.4908852  0.41959588 0.28567562 0.97616547 0.73157938]
 [0.59049223 0.50760273 0.25169001 0.82655621 0.95529182]]
New array= [[0.62417187 0.26976575 0.16580524 0.14824141 0.75917656]
 [0.12274187 0.87076401 0.15939465 0.16245522 0.96750397]
 [0.85711225 0.70324038 0.32441737 0.21844199 0.58730831]
 [0.29834035 0.75706156 0.07626642 0.18021305 0.31397457]
 [0.51121686 0.78273326 0.18743182 0.11838632 0.62552314]]


In [17]:
import numpy as np
x=np.random.random((5,5))
print(x)
max,min=x.max(),x.min()
print("Highest=",max,"Lowest=",min)

[[0.89726851 0.47056584 0.05390577 0.18064896 0.95384868]
 [0.13270654 0.73491847 0.27124927 0.6260837  0.50449008]
 [0.59536068 0.69919104 0.5863918  0.9970022  0.17218431]
 [0.09758967 0.17103129 0.03203774 0.85126372 0.1589967 ]
 [0.80621158 0.35297142 0.39576761 0.63031664 0.78559274]]
Highest= 0.9970022028218134 Lowest= 0.03203773677488886


In [18]:
import numpy as np
x=np.arange(1,11)
print(x)
np.random.shuffle(x)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 7  8  2  3 10  1  5  6  4  9]
